feat(bi): update pulumi version as needed (#2349)
I got an error this morning because the version I had didn't match the
go sdk version.

```
10:59:32.563 ERR cmd/root.go:39 Error executing command error="unable to start kube provider: error creating aws cluster: failed to refresh stack: failed to prepare refresh command: Pulumi CLI version >= 3.181.0 is required to use --client with refresh"
```

So let the automation API update the binary as needed.

Co-authored-by: Jason Tarasovic <2999202+JTarasovic@users.noreply.github.com>